UI: add inference flowunit creation

diff --git a/examples/bin/create b/examples/bin/create
--- a/examples/bin/create
+++ b/examples/bin/create
@@ -21,15 +21,19 @@ showhelp() {
 	echo " -t, --template=[c++|python|infer|project|service-plugin]    create a c++, python, inference, project, service-plugin template"
 	echo " -d, --dir=[directory]                target output directory, default is './'"
 	echo " -n, --name=[target-name]             target name, default is 'example'"
-	echo " --device=[device]                       target device, default is 'cpu'"
+	echo " --device=[device]                    target device, default is 'cpu'"
 	echo " --type=[type]                        target flowunit type, default is 'normal'"
 	echo " --desc=[desc]                 				target flowunit description, default is 'description'"
 	echo " --out=[outport]                 			target flowunit outport"
 	echo " --in=[inport]                 				target flowunit inport"
+	echo " --entry=[entry]                      entry path of model if target flowunit type is inference"
+	echo " --virutal=[virtual-type]             target inference flowunit type"
+	echo " --plugin=[plugin]             				engine plugin interface"
 }
 
 create_python_template()
 {
+	let base=44
 	if [ -e $directory/$name/$name.py ]; then 
 		return 0
 	fi
@@ -102,10 +106,10 @@ create_python_template()
 				return 1
 			fi
 			
-			sed -i "48 a\ \n" $directory/$name/$name.toml
+			sed -i "$(($base + 4)) a\ \n" $directory/$name/$name.toml
 		else
 			let i_plus=$i+1
-			let num_line=$i*5+44
+			let num_line=$i*5+$base
 			
 			sed -i "$num_line a\[output.output$i_plus]" $directory/$name/$name.toml
 			sed -i "$(($num_line + 1)) a\name = \"${out_array[i*3]}\"" $directory/$name/$name.toml
@@ -140,7 +144,7 @@ create_python_template()
 			fi
 		else
 			let i_plus=$i+1
-			let num_line=$i*5+37
+			let num_line=$i*5+$base-7
 			
 			sed -i "$num_line a\[input.input$i_plus]" $directory/$name/$name.toml
 			sed -i "$(($num_line + 1)) a\name = \"${in_array[i*3]}\"" $directory/$name/$name.toml
@@ -234,6 +238,111 @@ create_infer_template()
 		echo "sed CMakeLists.txt failed"
 		return 1
 	fi
+
+	sed -i "s/device = \"cuda\"/device = \"$device\"/g" $directory/$name/$name.toml
+	if [ $? -ne 0 ]; then
+		echo "add device failed"
+		return 1
+	fi
+
+	sed -i "s/\"description\"/\"$desc\"/g" $directory/$name/$name.toml
+	if [ $? -ne 0 ]; then
+		echo "add property description failed"
+		return 1
+	fi
+
+	sed -i "s/model.pb/$entry/g" $directory/$name/$name.toml
+	if [ $? -ne 0 ]; then
+		echo "add property description failed"
+		return 1
+	fi
+
+	sed -i "s/virtual_type = \"tensorflow\"/virtual_type = \"$virtual\"/g" $directory/$name/$name.toml
+	if [ $? -ne 0 ]; then
+		echo "add property description failed"
+		return 1
+	fi
+
+	sed -i "s/plugin = \"\"/plugin = \"$plugin\"/g" $directory/$name/$name.toml
+	if [ $? -ne 0 ]; then
+		echo "add property description failed"
+		return 1
+	fi
+
+	let base=37
+	for(( i=0;i<${#out_array[@]}/3;i++)) do
+		if [ $i -eq 0 ]; then
+			sed -i "s/out_1/${out_array[0]}/g" $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add output_$1 failed"
+				return 1
+			fi
+
+			sed -i "s/type = \"float\" # output/type = \"${out_array[2]}\" # output/g" $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add output_$1 failed"
+				return 1
+			fi
+
+			sed -i "s/device = \"cpu\" # output/device = \"${out_array[1]}\" # output/g" $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add output_$1 failed"
+				return 1
+			fi
+			
+			sed -i "$(($base + 4)) a\ \n" $directory/$name/$name.toml
+		else
+			let i_plus=$i+1
+			let num_line=$i*5+$base
+			
+			sed -i "$num_line a\[output.output$i_plus]" $directory/$name/$name.toml
+			sed -i "$(($num_line + 1)) a\name = \"${out_array[i*3]}\"" $directory/$name/$name.toml
+			sed -i "$(($num_line + 2)) a\type = \"${out_array[i*3+1]}\"" $directory/$name/$name.toml
+			sed -i "$(($num_line + 3)) a\device = \"${out_array[i*3+2]}\"" $directory/$name/$name.toml
+			sed -i "$(($num_line + 4)) a\ " $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add output_$1 failed"
+				return 1
+			fi
+		fi
+	done;
+	
+	for(( i=0;i<${#in_array[@]}/3;i++)) do
+		if [ $i -eq 0 ]; then
+			sed -i "s/in_1/${in_array[0]}/g" $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add input_$1 failed"
+				return 1
+			fi
+
+			sed -i "s/type = \"float\" # input/type = \"${in_array[2]}\" # input/g" $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add input_$1 failed"
+				return 1
+			fi
+
+			sed -i "s/device = \"cpu\" # input/device = \"${in_array[1]}\" # input/g" $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add input_$1 failed"
+				return 1
+			fi
+		else
+			let i_plus=$i+1
+			let num_line=$i*5+$base-7
+			
+			sed -i "$num_line a\[input.input$i_plus]" $directory/$name/$name.toml
+			sed -i "$(($num_line + 1)) a\name = \"${in_array[i*3]}\"" $directory/$name/$name.toml
+			sed -i "$(($num_line + 2)) a\type = \"${in_array[i*3+1]}\"" $directory/$name/$name.toml
+			sed -i "$(($num_line + 3)) a\device = \"${in_array[i*3+2]}\"" $directory/$name/$name.toml
+			sed -i "$(($num_line + 4)) a\ " $directory/$name/$name.toml
+			if [ $? -ne 0 ]; then
+				echo "add input_$1 failed"
+				return 1
+			fi
+		fi
+	done;
+
+	
 }
 
 create_project_template()
@@ -368,7 +477,7 @@ create_template()
 
 
 main() {
-	OPTS=`getopt -o n:t:d:h --long template:,name:,dir:,help:,desc:,device:,type:,in:,out \
+	OPTS=`getopt -o n:t:d:h --long template:,name:,dir:,help:,desc:,device:,type:,in:,out:,entry:,virtual:,plugin \
 		-n  "" -- "$@"`
 
 	if [ $# -lt 2 ]; then showhelp; exit 1; fi
@@ -389,6 +498,9 @@ main() {
 	in_num=0
 	in_array=()
 	out_array=()
+	entry="model.pb"
+	virtual="tensorflow"
+	plugin=""
 	
 
 	while true; do
@@ -413,6 +525,15 @@ main() {
 			shift 2;;
 		--desc)
 			desc="$2"
+			shift 2;;
+		--entry)
+			entry="$2"
+			shift 2;;
+		--virtual)
+			virtual="$2"
+			shift 2;;
+		--plugin)
+			plugin="$2"
 			shift 2;;
 		--in)
 			inport="$2"
